"""
provide exceptions for other modules
- these are custom exceptions used to make error handling easier
- none of them inherit from BaseException
"""


from sqlite3 import OperationalError

class InvalidInput(ValueError): ...
class InvalidUndeliveredString(InvalidInput): ...
class PaperAlreadyExists(OperationalError): ...
class PaperNotExists(OperationalError): ...
class StringNotExists(OperationalError): ...
class InvalidMonthYear(InvalidInput): ...
class NoParameters(ValueError): ...