from sqlite3 import DatabaseError, OperationalError

class InvalidInput(ValueError): ...
class InvalidUndeliveredString(InvalidInput): ...
class PaperAlreadyExists(OperationalError): ...
class PaperNotExists(OperationalError): ...
class StringNotExists(OperationalError): ...
class DatabaseFileError(DatabaseError): ...
class InvalidMonthYear(InvalidInput): ...
class NoParameters(ValueError): ...