on:
  push:
    branch:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        architecture: ['x64']
        app: ['cli', 'api']
        include:
          - os: windows
            data-file: "data/schema.sql;schema.sql"
          - os: macos
            data-file: "data/schema.sql:schema.sql"
          - os: ubuntu
            data-file: "data/schema.sql:schema.sql"
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.app }}-${{ matrix.os }}-${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: ${{ matrix.architecture }}
      - run: pip install -r requirements.txt pyinstaller
      - run: mkdir build
      - run: mkdir bin
      - run: pyinstaller --distpath bin --clean --add-data "${{ matrix.data-file }}" --onefile --name npbc_${{ matrix.app }}-${{ matrix.os }}-${{ matrix.architecture }} npbc_${{ matrix.app }}.py
      - uses: actions/upload-artifact@v2
        with:
          path: bin
          name: npbc_${{ matrix.app }}-${{ matrix.os }}-${{ matrix.architecture }}
  
  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: mkdir bin
    - uses: actions/download-artifact@v2
      with:
        path: bin
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/npbc*/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
        prerelease: true
