on: [push]

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        architecture: ['x64']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: ${{ matrix.architecture }}
      - run: pip install -r requirements.txt pyinstaller
      - run: mkdir build
      - run: mkdir bin
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: pyinstaller --distpath bin --clean npbc_cli.spec
      - uses: actions/upload-artifact@v2
        with:
          path: bin
          name: npbc_cli-${{ matrix.os }}-${{ matrix.architecture }}
      - run: tree .
  
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: bin
    - run: tree .
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./bin/*"
        token: ${{ secrets.GITHUB_TOKEN }}