on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    name: ${{ matrix.os }}
    steps:
      - run: pwd
      - run: ls -al $HOME
      # - name: Install Python dependencies
      #   uses: py-actions/py-dependency-install@v3
      # - run: python -m nuitka --include-data-file=/home/anujv/pts/npbc/data/schema.sql=schema.sql --onefile --standalone -o bin/executables/npbc_cli npbc_cli.py
