name: Test

on: [push]

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - run: wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
      - run: tar -xvf sqlite-autoconf-3380500.tar.gz
      - run: ls -al
        working-directory: sqlite-autoconf-3380500
      - run: pwd
        working-directory: sqlite-autoconf-3380500
      - run: ./configure
        working-directory: sqlite-autoconf-3380500
      - run: make
        working-directory: sqlite-autoconf-3380500
      - run: make install
        working-directory: sqlite-autoconf-3380500
      - run: export PATH="/usr/local/lib:$PATH"
      - run: sqlite3 --version

      - run: pip install -r requirements.txt pytest
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - run: pytest